### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Material#35] opened 2020-05-06 18:15 UTC
## What would you like to be added:
Buttons with Ripple effect
## Why is this needed:
Strong identity for Material Design
## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly

## Anything else we need to know?
Could look at how MaterialDesignInXaml did in WPF for inspiration
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Ripple.cs

**Comment by StewartPolsky** [comment] 2020-05-20 16:06
In Button Overview, on "TEXT" button there is no border, however the ripple effect does get cut off and shows a border

![Uno Material_Button Ripple](https://user-images.githubusercontent.com/49959074/82469677-5b8b9b00-9a92-11ea-90fc-c0e7993b5ebd.gif)

**Comment by StewartPolsky** [comment] 2020-05-20 18:00
On WASM, when clicking a button, the ripple effect is only displayed for the first click (for each button), and not the following clicks.

![Uno Material_Button WASM Ripple](https://user-images.githubusercontent.com/49959074/82480672-225b2700-9aa2-11ea-8a63-56b6799eeea2.gif)

**Comment by NicolasChampagne** [comment] 2020-05-21 17:22
> In Button Overview (Android), on "TEXT" button there is no border, however the ripple effect does get cut off and shows a border
> 
> ![Uno Material_Button Ripple](https://user-images.githubusercontent.com/49959074/82469677-5b8b9b00-9a92-11ea-90fc-c0e7993b5ebd.gif)

This occurs on every platform since this is a button... Do you want a bigger ripple to see the side borders as well.

**Comment by StewartPolsky** [comment] 2020-05-21 18:21
@MatFillion What is the expected behavior as the button does not have a visible border?

**Comment by MatFillion** [comment] 2020-05-21 20:38
As close as possible to what's specified on material.io 😃 @StewartPolsky

**Comment by MatFillion** [comment] 2020-05-22 04:43
Looking at https://material.io/design/interaction/states.html#pressed it seems both having a ripple that goes outside it's container and a ripple that stays within the bounds (even if no border) is OK. I think the current implementation show in your gif is correct..

For the wasm bug, we should have a github issue to track it. (if not already)

**Comment by Xiaoy312** [comment] 2020-06-03 19:43
@MatFillion Can we close this, since it is implemented.
@StewartPolsky If any of the bugs here are still valid, we can open a separate issue for them.

**Closed** 2020-06-03 19:49 UTC
